// Backward-compatible re-export. All actual logic lives in src/services/api.js
export {
  fetchFeatured,
  fetchPopular,
  fetchDestinations,
  fetchDestinationTypes,
  fetchDestinationById,
  fetchTestimonials,
  fetchReviewsByDestination,
  createBooking,
  fetchMyBookings,
  cancelMyBooking,
  updateMyProfile,
  changeMyPassword,
  fetchAdminStats,
  fetchAllBookings,
  updateBookingStatus,
  createDestination,
  updateDestination,
  deleteDestination,
  createTestimonial,
  updateTestimonial,
  deleteTestimonial,
  createUserTestimonial,
  fetchMyTestimonials,
  fetchWishlist,
  addWishlistItem,
  removeWishlistItem,
  syncWishlist,
  uploadImage,
  uploadImages,
  getAIStatus,
  isAIEnabledClient,
  aiChat,
  aiPlan,
  aiRecommend,
} from "./services/api";
